---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-deployment
  namespace: argocd
spec:
  project: default
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  source:
    helm:
      valueFiles:
        - harbor/values.yaml
        - harbor/ingress.yaml
    repoURL: https://helm.goharbor.io
    path: harbor
    targetRevision: 1.6.0
    paths:
      - harbor/ingress.yaml
  syncPolicy:
  automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  syncOptions:
      - CreateNamespace=true
